version: '3'
services:
  web:
    build: .
    container_name: offers_collector_web
    restart: unless-stopped
    command: python app.py
    ports:
      - "18831:18832"
    environment:
      - DB_NAME=${DB_NAME-offers_collector}
      - DB_USER=${DB_USER-collector}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT-5432}
      - DB_HOST=${DB_HOST-db}
      - COLLECTOR_CRON_SECONDS=${COLLECTOR_CRON_SECONDS-300}
    env_file:
      - .env
  collector:
    build: .
    container_name: offers_collector
    restart: unless-stopped
    volumes:
      - .api_key.json:/app/.api_key.json
    command: python collector.py
    environment:
      - POSTGRES_DB=${POSTGRES_DB-offers_collector}
      - POSTGRES_USER=${POSTGRES_USER-collector}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT-5432}
      - DB_HOST=${DB_HOST-db}
      - COLLECTOR_CRON_SECONDS=${COLLECTOR_CRON_SECONDS-300}
      - ACCOUNT_EMAIL=${ACCOUNT_EMAIL-ssomov@bitzlato.com}
      - API_KEY_ID=${API_KEY_ID-1}
    env_file:
      - .env
  db:
    image: postgres:14-alpine
    container_name: offers_collector_db
    restart: unless-stopped
    ports:
      - "${DB_PORT-6666}:${DB_PORT-6666}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB-offers_collector}
      - POSTGRES_USER=${POSTGRES_USER-collector}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: -p ${DB_PORT-6666}
    env_file:
      - .env




